name: Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --hidden-import=pygame gui.py
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/*.exe
